export const LOAD_SPACE_SUCCESS = 'LOAD_SPACE_SUCCESS';

export const LOAD_ZONE_SUCCESS = 'LOAD_ZONE_SUCCESS';

export const INIT_TENANT_VIEW_REQUEST = 'INIT_TENANT_VIEW_REQUEST';
export const INIT_TENANT_VIEW_SUCCESS = 'INIT_TENANT_VIEW_SUCCESS';

export const ALARM_LIST_VIEW_REQUEST = 'ALARM_LIST_VIEW_REQUEST';
export const ALARM_LIST_VIEW_SUCCESS = 'ALARM_LIST_VIEW_SUCCESS';
export const ALARM_RULES = 'ALARM_RULES';

export const LOAD_SERVICE_SUCCESS = 'LOAD_SPACE_SERVICE_REQUEST';

export const SWITCH_ZONE = 'SWITCH_ZONE';
export const SWITCH_ORG = 'SWITCH_ORG';
export const SWITCH_SPACE = 'SWITCH_SPACE';

export const RESET_APPLICATION = 'RESET_APPLICATION';

export const LOAD_THEME_SUCCESS = 'LOAD_THEME_SUCCESS';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';

export const LOAD_SYSTEM_SETTINGS_SUCCESS = 'LOAD_SYSTEM_SETTINGS_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const LOAD_CATEGORY = 'LOAD_CATEGORY';
export const IS_COLLAPSE = 'IS_COLLAPSE';

export const LOAD_QUOTA_FIELD = 'LOAD_QUOTA_FIELD';

export const SET_DEFAULT_ACTIVE_MENU = 'SET_DEFAULT_ACTIVE_MENU';

export const SET_SGM_LOGIN_URL = 'SET_SGM_LOGIN_URL';
export const SET_SGM_LOGOUT_URL = 'SET_SGM_LOGOUT_URL';
export const SET_SGM_SSO = 'SET_SGM_SSO';

export const LOAD_API_RESOURCE = 'LOAD_API_RESOURCE';
export const UPDATE_OPENED_MENUS = 'UPDATE_OPENED_MENUS';

export const FUll_SCREENED = 'FUll_SCREENED';
