export default [
  {
    kind: 'APIResourceList',
    groupVersion: 'v1',
    resources: [
      {
        name: 'bindings',
        singularName: '',
        namespaced: true,
        kind: 'Binding',
        verbs: ['create'],
      },
      {
        name: 'componentstatuses',
        singularName: '',
        namespaced: false,
        kind: 'ComponentStatus',
        verbs: ['get', 'list'],
        shortNames: ['cs'],
      },
      {
        name: 'configmaps',
        singularName: '',
        namespaced: true,
        kind: 'ConfigMap',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['cm'],
      },
      {
        name: 'endpoints',
        singularName: '',
        namespaced: true,
        kind: 'Endpoints',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ep'],
      },
      {
        name: 'events',
        singularName: '',
        namespaced: true,
        kind: 'Event',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ev'],
      },
      {
        name: 'limitranges',
        singularName: '',
        namespaced: true,
        kind: 'LimitRange',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['limits'],
      },
      {
        name: 'namespaces',
        singularName: '',
        namespaced: false,
        kind: 'Namespace',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ns'],
      },
      {
        name: 'namespaces/finalize',
        singularName: '',
        namespaced: false,
        kind: 'Namespace',
        verbs: ['update'],
      },
      {
        name: 'namespaces/status',
        singularName: '',
        namespaced: false,
        kind: 'Namespace',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'nodes',
        singularName: '',
        namespaced: false,
        kind: 'Node',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['no'],
      },
      {
        name: 'nodes/proxy',
        singularName: '',
        namespaced: false,
        kind: 'Node',
        verbs: [],
      },
      {
        name: 'nodes/status',
        singularName: '',
        namespaced: false,
        kind: 'Node',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'persistentvolumeclaims',
        singularName: '',
        namespaced: true,
        kind: 'PersistentVolumeClaim',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pvc'],
      },
      {
        name: 'persistentvolumeclaims/status',
        singularName: '',
        namespaced: true,
        kind: 'PersistentVolumeClaim',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'persistentvolumes',
        singularName: '',
        namespaced: false,
        kind: 'PersistentVolume',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pv'],
      },
      {
        name: 'persistentvolumes/status',
        singularName: '',
        namespaced: false,
        kind: 'PersistentVolume',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'pods',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['po'],
        categories: ['all'],
      },
      {
        name: 'pods/attach',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: [],
      },
      {
        name: 'pods/binding',
        singularName: '',
        namespaced: true,
        kind: 'Binding',
        verbs: ['create'],
      },
      {
        name: 'pods/eviction',
        singularName: '',
        namespaced: true,
        group: 'policy',
        version: 'v1beta1',
        kind: 'Eviction',
        verbs: ['create'],
      },
      {
        name: 'pods/exec',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: [],
      },
      {
        name: 'pods/log',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: ['get'],
      },
      {
        name: 'pods/portforward',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: [],
      },
      {
        name: 'pods/proxy',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: [],
      },
      {
        name: 'pods/status',
        singularName: '',
        namespaced: true,
        kind: 'Pod',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'podtemplates',
        singularName: '',
        namespaced: true,
        kind: 'PodTemplate',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'replicationcontrollers',
        singularName: '',
        namespaced: true,
        kind: 'ReplicationController',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['rc'],
        categories: ['all'],
      },
      {
        name: 'replicationcontrollers/scale',
        singularName: '',
        namespaced: true,
        group: 'autoscaling',
        version: 'v1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicationcontrollers/status',
        singularName: '',
        namespaced: true,
        kind: 'ReplicationController',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'resourcequotas',
        singularName: '',
        namespaced: true,
        kind: 'ResourceQuota',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['quota'],
      },
      {
        name: 'resourcequotas/status',
        singularName: '',
        namespaced: true,
        kind: 'ResourceQuota',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'secrets',
        singularName: '',
        namespaced: true,
        kind: 'Secret',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'securitycontextconstraints',
        singularName: '',
        namespaced: false,
        kind: 'SecurityContextConstraints',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['scc'],
      },
      {
        name: 'serviceaccounts',
        singularName: '',
        namespaced: true,
        kind: 'ServiceAccount',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sa'],
      },
      {
        name: 'services',
        singularName: '',
        namespaced: true,
        kind: 'Service',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['svc'],
        categories: ['all'],
      },
      {
        name: 'services/proxy',
        singularName: '',
        namespaced: true,
        kind: 'Service',
        verbs: [],
      },
      {
        name: 'services/status',
        singularName: '',
        namespaced: true,
        kind: 'Service',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apiregistration.k8s.io/v1',
    resources: [
      {
        name: 'apiservices',
        singularName: '',
        namespaced: false,
        kind: 'APIService',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'apiservices/status',
        singularName: '',
        namespaced: false,
        kind: 'APIService',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apiregistration.k8s.io/v1beta1',
    resources: [
      {
        name: 'apiservices',
        singularName: '',
        namespaced: false,
        kind: 'APIService',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'apiservices/status',
        singularName: '',
        namespaced: false,
        kind: 'APIService',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    groupVersion: 'extensions/v1beta1',
    resources: [
      {
        name: 'daemonsets',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ds'],
      },
      {
        name: 'daemonsets/status',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['deploy'],
      },
      {
        name: 'deployments/rollback',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentRollback',
        verbs: ['create'],
      },
      {
        name: 'deployments/scale',
        singularName: '',
        namespaced: true,
        group: 'extensions',
        version: 'v1beta1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments/status',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'ingresses',
        singularName: '',
        namespaced: true,
        kind: 'Ingress',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ing'],
      },
      {
        name: 'ingresses/status',
        singularName: '',
        namespaced: true,
        kind: 'Ingress',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'networkpolicies',
        singularName: '',
        namespaced: true,
        kind: 'NetworkPolicy',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['netpol'],
      },
      {
        name: 'podsecuritypolicies',
        singularName: '',
        namespaced: false,
        kind: 'PodSecurityPolicy',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['psp'],
      },
      {
        name: 'replicasets',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['rs'],
      },
      {
        name: 'replicasets/scale',
        singularName: '',
        namespaced: true,
        group: 'extensions',
        version: 'v1beta1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicasets/status',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicationcontrollers',
        singularName: '',
        namespaced: true,
        kind: 'ReplicationControllerDummy',
        verbs: [],
      },
      {
        name: 'replicationcontrollers/scale',
        singularName: '',
        namespaced: true,
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apps/v1',
    resources: [
      {
        name: 'controllerrevisions',
        singularName: '',
        namespaced: true,
        kind: 'ControllerRevision',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'daemonsets',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ds'],
        categories: ['all'],
      },
      {
        name: 'daemonsets/status',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['deploy'],
        categories: ['all'],
      },
      {
        name: 'deployments/scale',
        singularName: '',
        namespaced: true,
        group: 'autoscaling',
        version: 'v1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments/status',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicasets',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['rs'],
        categories: ['all'],
      },
      {
        name: 'replicasets/scale',
        singularName: '',
        namespaced: true,
        group: 'autoscaling',
        version: 'v1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicasets/status',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sts'],
        categories: ['all'],
      },
      {
        name: 'statefulsets/scale',
        singularName: '',
        namespaced: true,
        group: 'autoscaling',
        version: 'v1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets/status',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apps/v1beta2',
    resources: [
      {
        name: 'controllerrevisions',
        singularName: '',
        namespaced: true,
        kind: 'ControllerRevision',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'daemonsets',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ds'],
        categories: ['all'],
      },
      {
        name: 'daemonsets/status',
        singularName: '',
        namespaced: true,
        kind: 'DaemonSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['deploy'],
        categories: ['all'],
      },
      {
        name: 'deployments/scale',
        singularName: '',
        namespaced: true,
        group: 'apps',
        version: 'v1beta2',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments/status',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicasets',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['rs'],
        categories: ['all'],
      },
      {
        name: 'replicasets/scale',
        singularName: '',
        namespaced: true,
        group: 'apps',
        version: 'v1beta2',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'replicasets/status',
        singularName: '',
        namespaced: true,
        kind: 'ReplicaSet',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sts'],
        categories: ['all'],
      },
      {
        name: 'statefulsets/scale',
        singularName: '',
        namespaced: true,
        group: 'apps',
        version: 'v1beta2',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets/status',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apps/v1beta1',
    resources: [
      {
        name: 'controllerrevisions',
        singularName: '',
        namespaced: true,
        kind: 'ControllerRevision',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'deployments',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['deploy'],
        categories: ['all'],
      },
      {
        name: 'deployments/rollback',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentRollback',
        verbs: ['create'],
      },
      {
        name: 'deployments/scale',
        singularName: '',
        namespaced: true,
        group: 'apps',
        version: 'v1beta1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deployments/status',
        singularName: '',
        namespaced: true,
        kind: 'Deployment',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sts'],
        categories: ['all'],
      },
      {
        name: 'statefulsets/scale',
        singularName: '',
        namespaced: true,
        group: 'apps',
        version: 'v1beta1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'statefulsets/status',
        singularName: '',
        namespaced: true,
        kind: 'StatefulSet',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'events.k8s.io/v1beta1',
    resources: [
      {
        name: 'events',
        singularName: '',
        namespaced: true,
        kind: 'Event',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ev'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'authentication.k8s.io/v1',
    resources: [
      {
        name: 'tokenreviews',
        singularName: '',
        namespaced: false,
        kind: 'TokenReview',
        verbs: ['create'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'authentication.k8s.io/v1beta1',
    resources: [
      {
        name: 'tokenreviews',
        singularName: '',
        namespaced: false,
        kind: 'TokenReview',
        verbs: ['create'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'authorization.k8s.io/v1',
    resources: [
      {
        name: 'localsubjectaccessreviews',
        singularName: '',
        namespaced: true,
        kind: 'LocalSubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'selfsubjectaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'SelfSubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'selfsubjectrulesreviews',
        singularName: '',
        namespaced: false,
        kind: 'SelfSubjectRulesReview',
        verbs: ['create'],
      },
      {
        name: 'subjectaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'SubjectAccessReview',
        verbs: ['create'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'authorization.k8s.io/v1beta1',
    resources: [
      {
        name: 'localsubjectaccessreviews',
        singularName: '',
        namespaced: true,
        kind: 'LocalSubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'selfsubjectaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'SelfSubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'selfsubjectrulesreviews',
        singularName: '',
        namespaced: false,
        kind: 'SelfSubjectRulesReview',
        verbs: ['create'],
      },
      {
        name: 'subjectaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'SubjectAccessReview',
        verbs: ['create'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'autoscaling/v1',
    resources: [
      {
        name: 'horizontalpodautoscalers',
        singularName: '',
        namespaced: true,
        kind: 'HorizontalPodAutoscaler',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['hpa'],
        categories: ['all'],
      },
      {
        name: 'horizontalpodautoscalers/status',
        singularName: '',
        namespaced: true,
        kind: 'HorizontalPodAutoscaler',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'autoscaling/v2beta1',
    resources: [
      {
        name: 'horizontalpodautoscalers',
        singularName: '',
        namespaced: true,
        kind: 'HorizontalPodAutoscaler',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['hpa'],
        categories: ['all'],
      },
      {
        name: 'horizontalpodautoscalers/status',
        singularName: '',
        namespaced: true,
        kind: 'HorizontalPodAutoscaler',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'batch/v1',
    resources: [
      {
        name: 'jobs',
        singularName: '',
        namespaced: true,
        kind: 'Job',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        categories: ['all'],
      },
      {
        name: 'jobs/status',
        singularName: '',
        namespaced: true,
        kind: 'Job',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'batch/v1beta1',
    resources: [
      {
        name: 'cronjobs',
        singularName: '',
        namespaced: true,
        kind: 'CronJob',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['cj'],
        categories: ['all'],
      },
      {
        name: 'cronjobs/status',
        singularName: '',
        namespaced: true,
        kind: 'CronJob',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'certificates.k8s.io/v1beta1',
    resources: [
      {
        name: 'certificatesigningrequests',
        singularName: '',
        namespaced: false,
        kind: 'CertificateSigningRequest',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['csr'],
      },
      {
        name: 'certificatesigningrequests/approval',
        singularName: '',
        namespaced: false,
        kind: 'CertificateSigningRequest',
        verbs: ['update'],
      },
      {
        name: 'certificatesigningrequests/status',
        singularName: '',
        namespaced: false,
        kind: 'CertificateSigningRequest',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'networking.k8s.io/v1',
    resources: [
      {
        name: 'networkpolicies',
        singularName: '',
        namespaced: true,
        kind: 'NetworkPolicy',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['netpol'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'policy/v1beta1',
    resources: [
      {
        name: 'poddisruptionbudgets',
        singularName: '',
        namespaced: true,
        kind: 'PodDisruptionBudget',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pdb'],
      },
      {
        name: 'poddisruptionbudgets/status',
        singularName: '',
        namespaced: true,
        kind: 'PodDisruptionBudget',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'podsecuritypolicies',
        singularName: '',
        namespaced: false,
        kind: 'PodSecurityPolicy',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['psp'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'authorization.openshift.io/v1',
    resources: [
      {
        name: 'clusterrolebindings',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRoleBinding',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update'],
      },
      {
        name: 'clusterroles',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRole',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update'],
      },
      {
        name: 'localresourceaccessreviews',
        singularName: '',
        namespaced: true,
        kind: 'LocalResourceAccessReview',
        verbs: ['create'],
      },
      {
        name: 'localsubjectaccessreviews',
        singularName: '',
        namespaced: true,
        kind: 'LocalSubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'resourceaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'ResourceAccessReview',
        verbs: ['create'],
      },
      {
        name: 'rolebindingrestrictions',
        singularName: '',
        namespaced: true,
        kind: 'RoleBindingRestriction',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'rolebindings',
        singularName: '',
        namespaced: true,
        kind: 'RoleBinding',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update'],
      },
      {
        name: 'roles',
        singularName: '',
        namespaced: true,
        kind: 'Role',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update'],
      },
      {
        name: 'selfsubjectrulesreviews',
        singularName: '',
        namespaced: true,
        kind: 'SelfSubjectRulesReview',
        verbs: ['create'],
      },
      {
        name: 'subjectaccessreviews',
        singularName: '',
        namespaced: false,
        kind: 'SubjectAccessReview',
        verbs: ['create'],
      },
      {
        name: 'subjectrulesreviews',
        singularName: '',
        namespaced: true,
        kind: 'SubjectRulesReview',
        verbs: ['create'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'rbac.authorization.k8s.io/v1',
    resources: [
      {
        name: 'clusterrolebindings',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRoleBinding',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'clusterroles',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRole',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'rolebindings',
        singularName: '',
        namespaced: true,
        kind: 'RoleBinding',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'roles',
        singularName: '',
        namespaced: true,
        kind: 'Role',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'rbac.authorization.k8s.io/v1beta1',
    resources: [
      {
        name: 'clusterrolebindings',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRoleBinding',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'clusterroles',
        singularName: '',
        namespaced: false,
        kind: 'ClusterRole',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'rolebindings',
        singularName: '',
        namespaced: true,
        kind: 'RoleBinding',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'roles',
        singularName: '',
        namespaced: true,
        kind: 'Role',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'storage.k8s.io/v1',
    resources: [
      {
        name: 'storageclasses',
        singularName: '',
        namespaced: false,
        kind: 'StorageClass',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sc'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'storage.k8s.io/v1beta1',
    resources: [
      {
        name: 'storageclasses',
        singularName: '',
        namespaced: false,
        kind: 'StorageClass',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sc'],
      },
      {
        name: 'volumeattachments',
        singularName: '',
        namespaced: false,
        kind: 'VolumeAttachment',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'admissionregistration.k8s.io/v1beta1',
    resources: [
      {
        name: 'mutatingwebhookconfigurations',
        singularName: '',
        namespaced: false,
        kind: 'MutatingWebhookConfiguration',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'validatingwebhookconfigurations',
        singularName: '',
        namespaced: false,
        kind: 'ValidatingWebhookConfiguration',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apiextensions.k8s.io/v1beta1',
    resources: [
      {
        name: 'customresourcedefinitions',
        singularName: '',
        namespaced: false,
        kind: 'CustomResourceDefinition',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['crd', 'crds'],
      },
      {
        name: 'customresourcedefinitions/status',
        singularName: '',
        namespaced: false,
        kind: 'CustomResourceDefinition',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'scheduling.k8s.io/v1beta1',
    resources: [
      {
        name: 'priorityclasses',
        singularName: '',
        namespaced: false,
        kind: 'PriorityClass',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pc'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'apps.openshift.io/v1',
    resources: [
      {
        name: 'deploymentconfigs',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentConfig',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['dc'],
        categories: ['all'],
      },
      {
        name: 'deploymentconfigs/instantiate',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentRequest',
        verbs: ['create'],
      },
      {
        name: 'deploymentconfigs/log',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentLog',
        verbs: ['get'],
      },
      {
        name: 'deploymentconfigs/rollback',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentConfigRollback',
        verbs: ['create'],
      },
      {
        name: 'deploymentconfigs/scale',
        singularName: '',
        namespaced: true,
        group: 'extensions',
        version: 'v1beta1',
        kind: 'Scale',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'deploymentconfigs/status',
        singularName: '',
        namespaced: true,
        kind: 'DeploymentConfig',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'build.openshift.io/v1',
    resources: [
      {
        name: 'buildconfigs',
        singularName: '',
        namespaced: true,
        kind: 'BuildConfig',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['bc'],
        categories: ['all'],
      },
      {
        name: 'buildconfigs/instantiate',
        singularName: '',
        namespaced: true,
        kind: 'BuildRequest',
        verbs: ['create'],
      },
      {
        name: 'buildconfigs/instantiatebinary',
        singularName: '',
        namespaced: true,
        kind: 'BinaryBuildRequestOptions',
        verbs: [],
      },
      {
        name: 'buildconfigs/webhooks',
        singularName: '',
        namespaced: true,
        kind: 'Build',
        verbs: [],
      },
      {
        name: 'builds',
        singularName: '',
        namespaced: true,
        kind: 'Build',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        categories: ['all'],
      },
      {
        name: 'builds/clone',
        singularName: '',
        namespaced: true,
        kind: 'BuildRequest',
        verbs: ['create'],
      },
      {
        name: 'builds/details',
        singularName: '',
        namespaced: true,
        kind: 'Build',
        verbs: ['update'],
      },
      {
        name: 'builds/log',
        singularName: '',
        namespaced: true,
        kind: 'BuildLog',
        verbs: ['get'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'image.openshift.io/v1',
    resources: [
      {
        name: 'images',
        singularName: '',
        namespaced: false,
        kind: 'Image',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'imagesignatures',
        singularName: '',
        namespaced: false,
        kind: 'ImageSignature',
        verbs: ['create', 'delete'],
      },
      {
        name: 'imagestreamimages',
        singularName: '',
        namespaced: true,
        kind: 'ImageStreamImage',
        verbs: ['get'],
        shortNames: ['isimage'],
      },
      {
        name: 'imagestreamimports',
        singularName: '',
        namespaced: true,
        kind: 'ImageStreamImport',
        verbs: ['create'],
      },
      {
        name: 'imagestreammappings',
        singularName: '',
        namespaced: true,
        kind: 'ImageStreamMapping',
        verbs: ['create'],
      },
      {
        name: 'imagestreams',
        singularName: '',
        namespaced: true,
        kind: 'ImageStream',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['is'],
        categories: ['all'],
      },
      {
        name: 'imagestreams/layers',
        singularName: '',
        namespaced: true,
        kind: 'ImageStreamLayers',
        verbs: ['get'],
      },
      {
        name: 'imagestreams/secrets',
        singularName: '',
        namespaced: true,
        kind: 'SecretList',
        verbs: ['get'],
      },
      {
        name: 'imagestreams/status',
        singularName: '',
        namespaced: true,
        kind: 'ImageStream',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'imagestreamtags',
        singularName: '',
        namespaced: true,
        kind: 'ImageStreamTag',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update'],
        shortNames: ['istag'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'network.openshift.io/v1',
    resources: [
      {
        name: 'clusternetworks',
        singularName: '',
        namespaced: false,
        kind: 'ClusterNetwork',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'egressnetworkpolicies',
        singularName: '',
        namespaced: true,
        kind: 'EgressNetworkPolicy',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'hostsubnets',
        singularName: '',
        namespaced: false,
        kind: 'HostSubnet',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'netnamespaces',
        singularName: '',
        namespaced: false,
        kind: 'NetNamespace',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'oauth.openshift.io/v1',
    resources: [
      {
        name: 'oauthaccesstokens',
        singularName: '',
        namespaced: false,
        kind: 'OAuthAccessToken',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'oauthauthorizetokens',
        singularName: '',
        namespaced: false,
        kind: 'OAuthAuthorizeToken',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'oauthclientauthorizations',
        singularName: '',
        namespaced: false,
        kind: 'OAuthClientAuthorization',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'oauthclients',
        singularName: '',
        namespaced: false,
        kind: 'OAuthClient',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'project.openshift.io/v1',
    resources: [
      {
        name: 'projectrequests',
        singularName: '',
        namespaced: false,
        kind: 'ProjectRequest',
        verbs: ['create', 'list'],
      },
      {
        name: 'projects',
        singularName: '',
        namespaced: false,
        kind: 'Project',
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'quota.openshift.io/v1',
    resources: [
      {
        name: 'appliedclusterresourcequotas',
        singularName: '',
        namespaced: true,
        kind: 'AppliedClusterResourceQuota',
        verbs: ['get', 'list'],
      },
      {
        name: 'clusterresourcequotas',
        singularName: '',
        namespaced: false,
        kind: 'ClusterResourceQuota',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['clusterquota'],
      },
      {
        name: 'clusterresourcequotas/status',
        singularName: '',
        namespaced: false,
        kind: 'ClusterResourceQuota',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'route.openshift.io/v1',
    resources: [
      {
        name: 'routes',
        singularName: '',
        namespaced: true,
        kind: 'Route',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        categories: ['all'],
      },
      {
        name: 'routes/status',
        singularName: '',
        namespaced: true,
        kind: 'Route',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'security.openshift.io/v1',
    resources: [
      {
        name: 'podsecuritypolicyreviews',
        singularName: '',
        namespaced: true,
        kind: 'PodSecurityPolicyReview',
        verbs: ['create'],
      },
      {
        name: 'podsecuritypolicyselfsubjectreviews',
        singularName: '',
        namespaced: true,
        kind: 'PodSecurityPolicySelfSubjectReview',
        verbs: ['create'],
      },
      {
        name: 'podsecuritypolicysubjectreviews',
        singularName: '',
        namespaced: true,
        kind: 'PodSecurityPolicySubjectReview',
        verbs: ['create'],
      },
      {
        name: 'rangeallocations',
        singularName: '',
        namespaced: false,
        kind: 'RangeAllocation',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'securitycontextconstraints',
        singularName: '',
        namespaced: false,
        kind: 'SecurityContextConstraints',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['scc'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'template.openshift.io/v1',
    resources: [
      {
        name: 'brokertemplateinstances',
        singularName: '',
        namespaced: false,
        kind: 'BrokerTemplateInstance',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'processedtemplates',
        singularName: '',
        namespaced: true,
        kind: 'Template',
        verbs: ['create'],
      },
      {
        name: 'templateinstances',
        singularName: '',
        namespaced: true,
        kind: 'TemplateInstance',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'templateinstances/status',
        singularName: '',
        namespaced: true,
        kind: 'TemplateInstance',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'templates',
        singularName: '',
        namespaced: true,
        kind: 'Template',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'user.openshift.io/v1',
    resources: [
      {
        name: 'groups',
        singularName: '',
        namespaced: false,
        kind: 'Group',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'identities',
        singularName: '',
        namespaced: false,
        kind: 'Identity',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'useridentitymappings',
        singularName: '',
        namespaced: false,
        kind: 'UserIdentityMapping',
        verbs: ['create', 'delete', 'get', 'patch', 'update'],
      },
      {
        name: 'users',
        singularName: '',
        namespaced: false,
        kind: 'User',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'monitoring.coreos.com/v1',
    resources: [
      {
        name: 'servicemonitors',
        singularName: 'servicemonitor',
        namespaced: true,
        kind: 'ServiceMonitor',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'prometheusrules',
        singularName: 'prometheusrule',
        namespaced: true,
        kind: 'PrometheusRule',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'alertmanagers',
        singularName: 'alertmanager',
        namespaced: true,
        kind: 'Alertmanager',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'prometheuses',
        singularName: 'prometheus',
        namespaced: true,
        kind: 'Prometheus',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'automationbroker.io/v1alpha1',
    resources: [
      {
        name: 'bundlebindings',
        singularName: 'bundlebinding',
        namespaced: true,
        kind: 'BundleBinding',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'bundleinstances',
        singularName: 'bundleinstance',
        namespaced: true,
        kind: 'BundleInstance',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'bundles',
        singularName: 'bundle',
        namespaced: true,
        kind: 'Bundle',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'operators.coreos.com/v1alpha1',
    resources: [
      {
        name: 'clusterserviceversions',
        singularName: 'clusterserviceversion',
        namespaced: true,
        kind: 'ClusterServiceVersion',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
        shortNames: ['csv'],
        categories: ['all', 'olm'],
      },
      {
        name: 'clusterserviceversions/status',
        singularName: '',
        namespaced: true,
        kind: 'ClusterServiceVersion',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'installplans',
        singularName: 'installplan',
        namespaced: true,
        kind: 'InstallPlan',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
        categories: ['all', 'olm'],
      },
      {
        name: 'installplans/status',
        singularName: '',
        namespaced: true,
        kind: 'InstallPlan',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'subscriptions',
        singularName: 'subscription',
        namespaced: true,
        kind: 'Subscription',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
        categories: ['all', 'olm'],
      },
      {
        name: 'subscriptions/status',
        singularName: '',
        namespaced: true,
        kind: 'Subscription',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'catalogsources',
        singularName: 'catalogsource',
        namespaced: true,
        kind: 'CatalogSource',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
        categories: ['all', 'olm'],
      },
      {
        name: 'catalogsources/status',
        singularName: '',
        namespaced: true,
        kind: 'CatalogSource',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'etcd.database.coreos.com/v1beta2',
    resources: [
      {
        name: 'etcdbackups',
        singularName: 'etcdbackup',
        namespaced: true,
        kind: 'EtcdBackup',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
      {
        name: 'etcdclusters',
        singularName: 'etcdcluster',
        namespaced: true,
        kind: 'EtcdCluster',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
        shortNames: ['etcdclus', 'etcd'],
      },
      {
        name: 'etcdrestores',
        singularName: 'etcdrestore',
        namespaced: true,
        kind: 'EtcdRestore',
        verbs: ['delete', 'deletecollection', 'get', 'list', 'patch', 'create', 'update', 'watch'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'metrics.k8s.io/v1beta1',
    resources: [
      {
        name: 'nodes',
        singularName: '',
        namespaced: false,
        kind: 'NodeMetrics',
        verbs: ['get', 'list'],
      },
      {
        name: 'pods',
        singularName: '',
        namespaced: true,
        kind: 'PodMetrics',
        verbs: ['get', 'list'],
      },
    ],
  },
  {
    kind: 'APIResourceList',
    apiVersion: 'v1',
    groupVersion: 'servicecatalog.k8s.io/v1beta1',
    resources: [
      {
        name: 'clusterservicebrokers',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServiceBroker',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'clusterservicebrokers/status',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServiceBroker',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'clusterserviceclasses',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServiceClass',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'clusterserviceclasses/status',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServiceClass',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'clusterserviceplans',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServicePlan',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'clusterserviceplans/status',
        singularName: '',
        namespaced: false,
        kind: 'ClusterServicePlan',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'servicebindings',
        singularName: '',
        namespaced: true,
        kind: 'ServiceBinding',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'servicebindings/status',
        singularName: '',
        namespaced: true,
        kind: 'ServiceBinding',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'servicebrokers',
        singularName: '',
        namespaced: true,
        kind: 'ServiceBroker',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'servicebrokers/status',
        singularName: '',
        namespaced: true,
        kind: 'ServiceBroker',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'serviceclasses',
        singularName: '',
        namespaced: true,
        kind: 'ServiceClass',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'serviceclasses/status',
        singularName: '',
        namespaced: true,
        kind: 'ServiceClass',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'serviceinstances',
        singularName: '',
        namespaced: true,
        kind: 'ServiceInstance',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'serviceinstances/reference',
        singularName: '',
        namespaced: true,
        kind: 'ServiceInstance',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'serviceinstances/status',
        singularName: '',
        namespaced: true,
        kind: 'ServiceInstance',
        verbs: ['get', 'patch', 'update'],
      },
      {
        name: 'serviceplans',
        singularName: '',
        namespaced: true,
        kind: 'ServicePlan',
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
      },
      {
        name: 'serviceplans/status',
        singularName: '',
        namespaced: true,
        kind: 'ServicePlan',
        verbs: ['get', 'patch', 'update'],
      },
    ],
  },
];
