import api, { APIService } from './api';

const ROLE_TYPE = {
  PLATFORM: 'platform', // 平台角色
  NAMESPACE: 'namespace', // 项目组角色
};

class RoleService {
  api: APIService;

  constructor() {
    this.api = api;
  }

  list() {
    // return this.api.get('/auth/role');
    return Promise.resolve([
      {
        type: ROLE_TYPE.PLATFORM,
        name: '平台管理员',
        id: 'platform-manager',
        description: '超级管理员',
        update_time: Date.now(),
      },
      {
        type: ROLE_TYPE.PLATFORM,
        name: '项目组管理员',
        id: 'namespace-manager',
        description: '同时具备每个项目组负责人的权限',
        update_time: Date.now(),
      },
    ]);
  }

  get() {
    return this.api.get('/authorizations/roles/scope');
  }

  getRoles(params: object) {
    return this.api.get('/authorizations/roles', params);
  }

  // 获取指定用户角色列表接口
  getRolesById(params: object, userId: string) {
    return this.api.get(`/authorizations/users/${userId}/roles`, params);
  }

  // 用户设置角色
  setRole({ userId, roleId, data }: any) {
    return this.api.put(`/authorizations/users/${userId}/roles/${roleId}`, data);
  }

  // getPermission() {
  getPermission(roleId: string) {
    return this.api.get(`/authorizations/roles/${roleId}/permission`);
    // return Promise.resolve({
    //   id: '01E31SDP25FHCBBSS0MBF187KK',
    //   createdAt: '2020-03-10T16:36:48Z',
    //   updatedAt: '2020-03-10T16:36:48Z',
    //   name: 'root',
    //   featureCode: 'root',
    //   sort: 0,
    //   level: 0,
    //   access: true,
    //   children: [
    //     {
    //       id: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //       createdAt: '2020-03-10T16:36:48Z',
    //       updatedAt: '2020-03-10T16:36:48Z',
    //       name: '应用列表',
    //       type: 'page',
    //       featureCode: 'application',
    //       parentId: '01E31SDP25FHCBBSS0MBF187KK',
    //       sort: 0,
    //       level: 0,
    //       access: true,
    //       children: [
    //         {
    //           id: '01E31SDQT989N1JKVRNCZ9MSAF',
    //           createdAt: '2020-03-10T16:36:50Z',
    //           updatedAt: '2020-03-10T16:36:50Z',
    //           name: '删除',
    //           type: 'feature',
    //           featureCode: 'application.delete',
    //           featurePoint: true,
    //           parentId: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDR7JK5GTRGS2THBTNGM2',
    //               createdAt: '2020-03-10T16:36:50Z',
    //               updatedAt: '2020-03-10T16:36:50Z',
    //               type: 'api',
    //               featureCode: 'application.delete.api',
    //               parentId: '01E31SDQT989N1JKVRNCZ9MSAF',
    //               sort: 0,
    //               resourceActionId: '01E31SDR5EXBSXCR8YHV5GJWW3',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDRDWY1GY81TFVB6906G0',
    //           createdAt: '2020-03-10T16:36:50Z',
    //           updatedAt: '2020-03-10T16:36:50Z',
    //           name: '更新',
    //           type: 'feature',
    //           featureCode: 'application.update',
    //           featurePoint: true,
    //           parentId: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDRVY7RR4W5CV3K1E2KW8',
    //               createdAt: '2020-03-10T16:36:51Z',
    //               updatedAt: '2020-03-10T16:36:51Z',
    //               type: 'api',
    //               featureCode: 'application.update.api',
    //               parentId: '01E31SDRDWY1GY81TFVB6906G0',
    //               sort: 0,
    //               resourceActionId: '01E31SDRRXQRRDTE5VP0BA5YES',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDQ561SVHN798DCM84MWQ',
    //           createdAt: '2020-03-10T16:36:49Z',
    //           updatedAt: '2020-03-10T16:36:49Z',
    //           name: '查看',
    //           type: 'feature',
    //           featureCode: 'application.view',
    //           featurePoint: true,
    //           parentId: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDQNRMDF1E88M2G887AAS',
    //               createdAt: '2020-03-10T16:36:49Z',
    //               updatedAt: '2020-03-10T16:36:49Z',
    //               type: 'api',
    //               featureCode: 'application.view.api',
    //               parentId: '01E31SDQ561SVHN798DCM84MWQ',
    //               sort: 0,
    //               resourceActionId: '01E31SDQK8CCWT1H6ENZW0FEB7',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDPHTC4416KK6NXTAYXQ2',
    //           createdAt: '2020-03-10T16:36:48Z',
    //           updatedAt: '2020-03-10T16:36:48Z',
    //           name: '创建',
    //           type: 'feature',
    //           featureCode: 'application.create',
    //           featurePoint: true,
    //           parentId: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDQ06ZBK0SZZ36TSKCT8A',
    //               createdAt: '2020-03-10T16:36:49Z',
    //               updatedAt: '2020-03-10T16:36:49Z',
    //               type: 'api',
    //               featureCode: 'application.create.api',
    //               parentId: '01E31SDPHTC4416KK6NXTAYXQ2',
    //               sort: 0,
    //               resourceActionId: '01E31SDPXYBECH2TXVBWYVY22N',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDS0PMYYR3QPQBERDNWXX',
    //           createdAt: '2020-03-10T16:36:51Z',
    //           updatedAt: '2020-03-10T16:36:51Z',
    //           name: '查看监控',
    //           type: 'feature',
    //           featureCode: 'application.monitor',
    //           featurePoint: true,
    //           parentId: '01E31SDPBXG0TP1S87Y3FY2PTR',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //         },
    //       ],
    //     },
    //     {
    //       id: '01E31SDS5970E1MWFPJMM2T3R1',
    //       createdAt: '2020-03-10T16:36:51Z',
    //       updatedAt: '2020-03-10T16:36:51Z',
    //       name: '资源对象',
    //       type: 'page',
    //       featureCode: 'resource',
    //       parentId: '01E31SDP25FHCBBSS0MBF187KK',
    //       sort: 0,
    //       level: 0,
    //       access: true,
    //       children: [
    //         {
    //           id: '01E31SE5M651H54H3JEDJCPMAH',
    //           createdAt: '2020-03-10T16:37:04Z',
    //           updatedAt: '2020-03-10T16:37:04Z',
    //           name: 'ConfigMap',
    //           type: 'page',
    //           featureCode: 'configMap',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SE71KBN69WT60Y34249BK',
    //               createdAt: '2020-03-10T16:37:05Z',
    //               updatedAt: '2020-03-10T16:37:05Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'configMap.delete',
    //               featurePoint: true,
    //               parentId: '01E31SE5M651H54H3JEDJCPMAH',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE7GNY70T2QAE3CB25VY8',
    //                   createdAt: '2020-03-10T16:37:06Z',
    //                   updatedAt: '2020-03-10T16:37:06Z',
    //                   type: 'api',
    //                   featureCode: 'configMap.delete.api',
    //                   parentId: '01E31SE71KBN69WT60Y34249BK',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE7DW8MYBN196E708E7S3',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE7MYGGK5HQ27FJFJ37EA',
    //               createdAt: '2020-03-10T16:37:06Z',
    //               updatedAt: '2020-03-10T16:37:06Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'configMap.update',
    //               featurePoint: true,
    //               parentId: '01E31SE5M651H54H3JEDJCPMAH',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE82WKR3A6GVSRCTYFEPF',
    //                   createdAt: '2020-03-10T16:37:06Z',
    //                   updatedAt: '2020-03-10T16:37:06Z',
    //                   type: 'api',
    //                   featureCode: 'configMap.update.api',
    //                   parentId: '01E31SE7MYGGK5HQ27FJFJ37EA',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE80FZD9W4ZP7PTQ5H4GM',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE5SJM2SSGHM6RXVHMQ2N',
    //               createdAt: '2020-03-10T16:37:04Z',
    //               updatedAt: '2020-03-10T16:37:04Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'configMap.create',
    //               featurePoint: true,
    //               parentId: '01E31SE5M651H54H3JEDJCPMAH',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE683ZH6QGQ6XNFCACX0G',
    //                   createdAt: '2020-03-10T16:37:04Z',
    //                   updatedAt: '2020-03-10T16:37:04Z',
    //                   type: 'api',
    //                   featureCode: 'configMap.create.api',
    //                   parentId: '01E31SE5SJM2SSGHM6RXVHMQ2N',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE661KY89150SYBY57MXN',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE6DENB0AJ0E21W98Q21B',
    //               createdAt: '2020-03-10T16:37:05Z',
    //               updatedAt: '2020-03-10T16:37:05Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'configMap.view',
    //               featurePoint: true,
    //               parentId: '01E31SE5M651H54H3JEDJCPMAH',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE6VK28P8XDVSGFWAP7C3',
    //                   createdAt: '2020-03-10T16:37:05Z',
    //                   updatedAt: '2020-03-10T16:37:05Z',
    //                   type: 'api',
    //                   featureCode: 'configMap.view.api',
    //                   parentId: '01E31SE6DENB0AJ0E21W98Q21B',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE6SAMT9DNXA131YEV423',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SE0JZS6NA5C0JA0XV9VGB',
    //           createdAt: '2020-03-10T16:36:59Z',
    //           updatedAt: '2020-03-10T16:36:59Z',
    //           name: 'Service',
    //           type: 'page',
    //           featureCode: 'service',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SE207984PDYQQ57N574QW',
    //               createdAt: '2020-03-10T16:37:00Z',
    //               updatedAt: '2020-03-10T16:37:00Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'service.delete',
    //               featurePoint: true,
    //               parentId: '01E31SE0JZS6NA5C0JA0XV9VGB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE2DW8AN0PD58V8Q4TWBS',
    //                   createdAt: '2020-03-10T16:37:00Z',
    //                   updatedAt: '2020-03-10T16:37:00Z',
    //                   type: 'api',
    //                   featureCode: 'service.delete.api',
    //                   parentId: '01E31SE207984PDYQQ57N574QW',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE2BR2XN7H1PXBRYJ5NAE',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE1CB45NMDD751JXBPRVC',
    //               createdAt: '2020-03-10T16:36:59Z',
    //               updatedAt: '2020-03-10T16:36:59Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'service.view',
    //               featurePoint: true,
    //               parentId: '01E31SE0JZS6NA5C0JA0XV9VGB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE1VF0RCZTPAP9KZJY38E',
    //                   createdAt: '2020-03-10T16:37:00Z',
    //                   updatedAt: '2020-03-10T16:37:00Z',
    //                   type: 'api',
    //                   featureCode: 'service.view.api',
    //                   parentId: '01E31SE1CB45NMDD751JXBPRVC',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE1SAET4ADTYWFWSJAQCD',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE2K4DCVF47E34XC7APBP',
    //               createdAt: '2020-03-10T16:37:01Z',
    //               updatedAt: '2020-03-10T16:37:01Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'service.update',
    //               featurePoint: true,
    //               parentId: '01E31SE0JZS6NA5C0JA0XV9VGB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE30YS1C88CSK6Z0XT1TF',
    //                   createdAt: '2020-03-10T16:37:01Z',
    //                   updatedAt: '2020-03-10T16:37:01Z',
    //                   type: 'api',
    //                   featureCode: 'service.update.api',
    //                   parentId: '01E31SE2K4DCVF47E34XC7APBP',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE2YMDNA5QSRKD0XY68N6',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE0QBVCW8N3P3KD8WV77R',
    //               createdAt: '2020-03-10T16:36:59Z',
    //               updatedAt: '2020-03-10T16:36:59Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'service.create',
    //               featurePoint: true,
    //               parentId: '01E31SE0JZS6NA5C0JA0XV9VGB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE174F2X2P6BYDYZD473P',
    //                   createdAt: '2020-03-10T16:36:59Z',
    //                   updatedAt: '2020-03-10T16:36:59Z',
    //                   type: 'api',
    //                   featureCode: 'service.create.api',
    //                   parentId: '01E31SE0QBVCW8N3P3KD8WV77R',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE14WNSQ5YCZE39S0N756',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDYGM5HN02AJS9E37K4X9',
    //           createdAt: '2020-03-10T16:36:56Z',
    //           updatedAt: '2020-03-10T16:36:56Z',
    //           name: 'Pod',
    //           type: 'page',
    //           featureCode: 'pod',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDZ89WY9HKV6PSNR9VTPN',
    //               createdAt: '2020-03-10T16:36:57Z',
    //               updatedAt: '2020-03-10T16:36:57Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'pod.delete',
    //               featurePoint: true,
    //               parentId: '01E31SDYGM5HN02AJS9E37K4X9',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDZPX6GHV9QT4PGHKJPJR',
    //                   createdAt: '2020-03-10T16:36:58Z',
    //                   updatedAt: '2020-03-10T16:36:58Z',
    //                   type: 'api',
    //                   featureCode: 'pod.delete.api',
    //                   parentId: '01E31SDZ89WY9HKV6PSNR9VTPN',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDZMPB7WAC2EYA7GC6T3M',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDZVPNPS5RG2JTB3Y1PM9',
    //               createdAt: '2020-03-10T16:36:58Z',
    //               updatedAt: '2020-03-10T16:36:58Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'pod.update',
    //               featurePoint: true,
    //               parentId: '01E31SDYGM5HN02AJS9E37K4X9',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE09N0PNXJSC925NKK3PD',
    //                   createdAt: '2020-03-10T16:36:58Z',
    //                   updatedAt: '2020-03-10T16:36:58Z',
    //                   type: 'api',
    //                   featureCode: 'pod.update.api',
    //                   parentId: '01E31SDZVPNPS5RG2JTB3Y1PM9',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE07C153K86S289397ZJH',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE0E78A2ERV55NCBSBVVN',
    //               createdAt: '2020-03-10T16:36:58Z',
    //               updatedAt: '2020-03-10T16:36:58Z',
    //               name: '查看监控',
    //               type: 'feature',
    //               featureCode: 'application.monitor',
    //               featurePoint: true,
    //               parentId: '01E31SDYGM5HN02AJS9E37K4X9',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //             },
    //             {
    //               id: '01E31SDYN1SX2QYQNX8F5PJE3B',
    //               createdAt: '2020-03-10T16:36:57Z',
    //               updatedAt: '2020-03-10T16:36:57Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'pod.view',
    //               featurePoint: true,
    //               parentId: '01E31SDYGM5HN02AJS9E37K4X9',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDZ41WG4R06983DQCEYC2',
    //                   createdAt: '2020-03-10T16:36:57Z',
    //                   updatedAt: '2020-03-10T16:36:57Z',
    //                   type: 'api',
    //                   featureCode: 'pod.view.api',
    //                   parentId: '01E31SDYN1SX2QYQNX8F5PJE3B',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDZ1GQQGMZZ9R312NRVB9',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDVX308P6VAM7DJZWRD9Y',
    //           createdAt: '2020-03-10T16:36:54Z',
    //           updatedAt: '2020-03-10T16:36:54Z',
    //           name: 'StatefulSet',
    //           type: 'page',
    //           featureCode: 'statefulSet',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDWP9E6MDDARBEB2D3Z0H',
    //               createdAt: '2020-03-10T16:36:55Z',
    //               updatedAt: '2020-03-10T16:36:55Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'statefulSet.view',
    //               featurePoint: true,
    //               parentId: '01E31SDVX308P6VAM7DJZWRD9Y',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDX4A99RHXH4YCM0FXGXQ',
    //                   createdAt: '2020-03-10T16:36:55Z',
    //                   updatedAt: '2020-03-10T16:36:55Z',
    //                   type: 'api',
    //                   featureCode: 'statefulSet.view.api',
    //                   parentId: '01E31SDWP9E6MDDARBEB2D3Z0H',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDX26T99H3ZD451HBF848',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDX9S7BW909636M5MV05J',
    //               createdAt: '2020-03-10T16:36:55Z',
    //               updatedAt: '2020-03-10T16:36:55Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'statefulSet.delete',
    //               featurePoint: true,
    //               parentId: '01E31SDVX308P6VAM7DJZWRD9Y',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDXR5SSKJMFSG9DH0HKDS',
    //                   createdAt: '2020-03-10T16:36:56Z',
    //                   updatedAt: '2020-03-10T16:36:56Z',
    //                   type: 'api',
    //                   featureCode: 'statefulSet.delete.api',
    //                   parentId: '01E31SDX9S7BW909636M5MV05J',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDXNH2GABYKES5GVQ3CDG',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDXWVTMNK0DXNAFRG14MX',
    //               createdAt: '2020-03-10T16:36:56Z',
    //               updatedAt: '2020-03-10T16:36:56Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'statefulSet.update',
    //               featurePoint: true,
    //               parentId: '01E31SDVX308P6VAM7DJZWRD9Y',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDYBEK3JVEVZ68N5R53PW',
    //                   createdAt: '2020-03-10T16:36:56Z',
    //                   updatedAt: '2020-03-10T16:36:56Z',
    //                   type: 'api',
    //                   featureCode: 'statefulSet.update.api',
    //                   parentId: '01E31SDXWVTMNK0DXNAFRG14MX',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDY97X5VH0PX2HJYBHA36',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDW1ETRVG4YGR8XWF216S',
    //               createdAt: '2020-03-10T16:36:54Z',
    //               updatedAt: '2020-03-10T16:36:54Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'statefulSet.create',
    //               featurePoint: true,
    //               parentId: '01E31SDVX308P6VAM7DJZWRD9Y',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDWHKJSBSW8M34GJ35ZA0',
    //                   createdAt: '2020-03-10T16:36:54Z',
    //                   updatedAt: '2020-03-10T16:36:54Z',
    //                   type: 'api',
    //                   featureCode: 'statefulSet.create.api',
    //                   parentId: '01E31SDW1ETRVG4YGR8XWF216S',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDWF5KK6HTZQAW42D43BE',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SEAQ5S294T0AXFG6KKJGG',
    //           createdAt: '2020-03-10T16:37:09Z',
    //           updatedAt: '2020-03-10T16:37:09Z',
    //           name: 'PersistentVolumeClaim',
    //           type: 'page',
    //           featureCode: 'pvc',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SECPC7E39FADRQH1FQX92',
    //               createdAt: '2020-03-10T16:37:11Z',
    //               updatedAt: '2020-03-10T16:37:11Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'pvc.update',
    //               featurePoint: true,
    //               parentId: '01E31SEAQ5S294T0AXFG6KKJGG',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SED6B674J1T3T1M6Q58H4',
    //                   createdAt: '2020-03-10T16:37:11Z',
    //                   updatedAt: '2020-03-10T16:37:11Z',
    //                   type: 'api',
    //                   featureCode: 'pvc.update.api',
    //                   parentId: '01E31SECPC7E39FADRQH1FQX92',
    //                   sort: 0,
    //                   resourceActionId: '01E31SED42ES7N5FG9JWEP1T04',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SEAVJ2CVNWXDNZZP6B55D',
    //               createdAt: '2020-03-10T16:37:09Z',
    //               updatedAt: '2020-03-10T16:37:09Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'pvc.create',
    //               featurePoint: true,
    //               parentId: '01E31SEAQ5S294T0AXFG6KKJGG',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SEBB3885M6TEJQ3XBK5DT',
    //                   createdAt: '2020-03-10T16:37:10Z',
    //                   updatedAt: '2020-03-10T16:37:10Z',
    //                   type: 'api',
    //                   featureCode: 'pvc.create.api',
    //                   parentId: '01E31SEAVJ2CVNWXDNZZP6B55D',
    //                   sort: 0,
    //                   resourceActionId: '01E31SEB7HCZ4P205CAMWJ083N',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SEC2W3H1YB1E9C88FCKB3',
    //               createdAt: '2020-03-10T16:37:10Z',
    //               updatedAt: '2020-03-10T16:37:10Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'pvc.delete',
    //               featurePoint: true,
    //               parentId: '01E31SEAQ5S294T0AXFG6KKJGG',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SECJ162CEK9FPFTRD149T',
    //                   createdAt: '2020-03-10T16:37:11Z',
    //                   updatedAt: '2020-03-10T16:37:11Z',
    //                   type: 'api',
    //                   featureCode: 'pvc.delete.api',
    //                   parentId: '01E31SEC2W3H1YB1E9C88FCKB3',
    //                   sort: 0,
    //                   resourceActionId: '01E31SECFXC5JCEWN2D25V2SH9',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SEBFHK9S51FYY0SW1E8FZ',
    //               createdAt: '2020-03-10T16:37:10Z',
    //               updatedAt: '2020-03-10T16:37:10Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'pvc.view',
    //               featurePoint: true,
    //               parentId: '01E31SEAQ5S294T0AXFG6KKJGG',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SEBYCWQ6DBVBG22539E48',
    //                   createdAt: '2020-03-10T16:37:10Z',
    //                   updatedAt: '2020-03-10T16:37:10Z',
    //                   type: 'api',
    //                   featureCode: 'pvc.view.api',
    //                   parentId: '01E31SEBFHK9S51FYY0SW1E8FZ',
    //                   sort: 0,
    //                   resourceActionId: '01E31SEBW4D88MCZWY1C0806M6',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SE876ACEGW0X1N20020AE',
    //           createdAt: '2020-03-10T16:37:06Z',
    //           updatedAt: '2020-03-10T16:37:06Z',
    //           name: 'Secret',
    //           type: 'page',
    //           featureCode: 'secret',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SE8C51BM993BVB3NY62M2',
    //               createdAt: '2020-03-10T16:37:07Z',
    //               updatedAt: '2020-03-10T16:37:07Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'secret.create',
    //               featurePoint: true,
    //               parentId: '01E31SE876ACEGW0X1N20020AE',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE8SN2Z6ZR9H6H5PE6N3H',
    //                   createdAt: '2020-03-10T16:37:07Z',
    //                   updatedAt: '2020-03-10T16:37:07Z',
    //                   type: 'api',
    //                   featureCode: 'secret.create.api',
    //                   parentId: '01E31SE8C51BM993BVB3NY62M2',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE8QFS9Q6N4H5C7C09WGX',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE9HMZAHEHPAZHE97JH7M',
    //               createdAt: '2020-03-10T16:37:08Z',
    //               updatedAt: '2020-03-10T16:37:08Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'secret.delete',
    //               featurePoint: true,
    //               parentId: '01E31SE876ACEGW0X1N20020AE',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE9ZF6GEBY8Q574XHY8CY',
    //                   createdAt: '2020-03-10T16:37:08Z',
    //                   updatedAt: '2020-03-10T16:37:08Z',
    //                   type: 'api',
    //                   featureCode: 'secret.delete.api',
    //                   parentId: '01E31SE9HMZAHEHPAZHE97JH7M',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE9X6XVXE9RKQ340S5ZYD',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE8YX18CP9FP8DNXZMC4A',
    //               createdAt: '2020-03-10T16:37:07Z',
    //               updatedAt: '2020-03-10T16:37:07Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'secret.view',
    //               featurePoint: true,
    //               parentId: '01E31SE876ACEGW0X1N20020AE',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE9CM1E8NC90QCGHT7X1H',
    //                   createdAt: '2020-03-10T16:37:08Z',
    //                   updatedAt: '2020-03-10T16:37:08Z',
    //                   type: 'api',
    //                   featureCode: 'secret.view.api',
    //                   parentId: '01E31SE8YX18CP9FP8DNXZMC4A',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE9AFKE93KERRJ6NCEFWZ',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SEA4HRBT2BRBJKD2XNHH3',
    //               createdAt: '2020-03-10T16:37:08Z',
    //               updatedAt: '2020-03-10T16:37:08Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'secret.update',
    //               featurePoint: true,
    //               parentId: '01E31SE876ACEGW0X1N20020AE',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SEAJKJW25Y7XVZ1ZMGGGY',
    //                   createdAt: '2020-03-10T16:37:09Z',
    //                   updatedAt: '2020-03-10T16:37:09Z',
    //                   type: 'api',
    //                   featureCode: 'secret.update.api',
    //                   parentId: '01E31SEA4HRBT2BRBJKD2XNHH3',
    //                   sort: 0,
    //                   resourceActionId: '01E31SEAG5EEJSN817E9ZJYJPQ',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SDS9W9RDADCBN7PAH5CW0',
    //           createdAt: '2020-03-10T16:36:51Z',
    //           updatedAt: '2020-03-10T16:36:51Z',
    //           name: 'Deployment',
    //           type: 'page',
    //           featureCode: 'deployment',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SDTPPF93KX5YDPPQXDFEH',
    //               createdAt: '2020-03-10T16:36:53Z',
    //               updatedAt: '2020-03-10T16:36:53Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'deployment.delete',
    //               featurePoint: true,
    //               parentId: '01E31SDS9W9RDADCBN7PAH5CW0',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDV4NJ1CNGWK62MRY8RX9',
    //                   createdAt: '2020-03-10T16:36:53Z',
    //                   updatedAt: '2020-03-10T16:36:53Z',
    //                   type: 'api',
    //                   featureCode: 'deployment.delete.api',
    //                   parentId: '01E31SDTPPF93KX5YDPPQXDFEH',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDV2G388NACKVJXRSSWE7',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDV9N3QMNCK6J23G9T9X5',
    //               createdAt: '2020-03-10T16:36:53Z',
    //               updatedAt: '2020-03-10T16:36:53Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'deployment.update',
    //               featurePoint: true,
    //               parentId: '01E31SDS9W9RDADCBN7PAH5CW0',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDVR7MJ6HFHGEWP57ZB9Z',
    //                   createdAt: '2020-03-10T16:36:54Z',
    //                   updatedAt: '2020-03-10T16:36:54Z',
    //                   type: 'api',
    //                   featureCode: 'deployment.update.api',
    //                   parentId: '01E31SDV9N3QMNCK6J23G9T9X5',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDVNRGQ0T3CJ46G64VPS5',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDSEKJTSX9A0ZNPX433WV',
    //               createdAt: '2020-03-10T16:36:51Z',
    //               updatedAt: '2020-03-10T16:36:51Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'deployment.create',
    //               featurePoint: true,
    //               parentId: '01E31SDS9W9RDADCBN7PAH5CW0',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDSXYA6SNBS9NQ1E0KD9E',
    //                   createdAt: '2020-03-10T16:36:52Z',
    //                   updatedAt: '2020-03-10T16:36:52Z',
    //                   type: 'api',
    //                   featureCode: 'deployment.create.api',
    //                   parentId: '01E31SDSEKJTSX9A0ZNPX433WV',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDSVJSBVZQ4NCA29QHM4H',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SDT3EKAXQG31V9J8S6GJG',
    //               createdAt: '2020-03-10T16:36:52Z',
    //               updatedAt: '2020-03-10T16:36:52Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'deployment.view',
    //               featurePoint: true,
    //               parentId: '01E31SDS9W9RDADCBN7PAH5CW0',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SDTH3N29NP5XZRK4VZJ83',
    //                   createdAt: '2020-03-10T16:36:52Z',
    //                   updatedAt: '2020-03-10T16:36:52Z',
    //                   type: 'api',
    //                   featureCode: 'deployment.view.api',
    //                   parentId: '01E31SDT3EKAXQG31V9J8S6GJG',
    //                   sort: 0,
    //                   resourceActionId: '01E31SDTEYJXPR56T5YVTSV1BR',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SE35KA5J5TT0SYY1RP1DB',
    //           createdAt: '2020-03-10T16:37:01Z',
    //           updatedAt: '2020-03-10T16:37:01Z',
    //           name: 'Ingress',
    //           type: 'page',
    //           featureCode: 'ingress',
    //           parentId: '01E31SDS5970E1MWFPJMM2T3R1',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SE3WJ5P22Z9G0XX3GQ6SN',
    //               createdAt: '2020-03-10T16:37:02Z',
    //               updatedAt: '2020-03-10T16:37:02Z',
    //               name: '查看',
    //               type: 'feature',
    //               featureCode: 'ingress.view',
    //               featurePoint: true,
    //               parentId: '01E31SE35KA5J5TT0SYY1RP1DB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE4ABZXA8JK8HWFH1EYYM',
    //                   createdAt: '2020-03-10T16:37:02Z',
    //                   updatedAt: '2020-03-10T16:37:02Z',
    //                   type: 'api',
    //                   featureCode: 'ingress.view.api',
    //                   parentId: '01E31SE3WJ5P22Z9G0XX3GQ6SN',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE47WCM97GV3PSEQGMB73',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE4ENZPY5QJKGE4YZCH1H',
    //               createdAt: '2020-03-10T16:37:03Z',
    //               updatedAt: '2020-03-10T16:37:03Z',
    //               name: '删除',
    //               type: 'feature',
    //               featureCode: 'ingress.delete',
    //               featurePoint: true,
    //               parentId: '01E31SE35KA5J5TT0SYY1RP1DB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE4X5YQCED4VZSMSH4KN7',
    //                   createdAt: '2020-03-10T16:37:03Z',
    //                   updatedAt: '2020-03-10T16:37:03Z',
    //                   type: 'api',
    //                   featureCode: 'ingress.delete.api',
    //                   parentId: '01E31SE4ENZPY5QJKGE4YZCH1H',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE4SZWCZ3GAS15P75SZD0',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE39YKDTRACV06V2BRW1A',
    //               createdAt: '2020-03-10T16:37:01Z',
    //               updatedAt: '2020-03-10T16:37:01Z',
    //               name: '创建',
    //               type: 'feature',
    //               featureCode: 'ingress.create',
    //               featurePoint: true,
    //               parentId: '01E31SE35KA5J5TT0SYY1RP1DB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE3QN0MHW78ZWT160DRKX',
    //                   createdAt: '2020-03-10T16:37:02Z',
    //                   updatedAt: '2020-03-10T16:37:02Z',
    //                   type: 'api',
    //                   featureCode: 'ingress.create.api',
    //                   parentId: '01E31SE39YKDTRACV06V2BRW1A',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE3NCTFWW1Q0A2KC3XM9H',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //             {
    //               id: '01E31SE51F6VDD2PH5Z0TVYA11',
    //               createdAt: '2020-03-10T16:37:03Z',
    //               updatedAt: '2020-03-10T16:37:03Z',
    //               name: '更新',
    //               type: 'feature',
    //               featureCode: 'ingress.update',
    //               featurePoint: true,
    //               parentId: '01E31SE35KA5J5TT0SYY1RP1DB',
    //               sort: 0,
    //               level: 0,
    //               access: true,
    //               children: [
    //                 {
    //                   id: '01E31SE5FQP9XT81JVQB0Y54R7',
    //                   createdAt: '2020-03-10T16:37:04Z',
    //                   updatedAt: '2020-03-10T16:37:04Z',
    //                   type: 'api',
    //                   featureCode: 'ingress.update.api',
    //                   parentId: '01E31SE51F6VDD2PH5Z0TVYA11',
    //                   sort: 0,
    //                   resourceActionId: '01E31SE5D0Q4GK49RXDAZ7S4ET',
    //                   level: 0,
    //                   access: true,
    //                 },
    //               ],
    //             },
    //           ],
    //         },
    //       ],
    //     },
    //     {
    //       id: '01E31SEDAS2J275A4WWPHPKZAC',
    //       createdAt: '2020-03-10T16:37:12Z',
    //       updatedAt: '2020-03-10T16:37:12Z',
    //       name: '服务目录',
    //       type: 'page',
    //       featureCode: 'serviceCatalog',
    //       parentId: '01E31SDP25FHCBBSS0MBF187KK',
    //       sort: 0,
    //       level: 0,
    //       access: true,
    //       children: [
    //         {
    //           id: '01E31SEF6XBKBA9CGWF7H1D6QK',
    //           createdAt: '2020-03-10T16:37:14Z',
    //           updatedAt: '2020-03-10T16:37:14Z',
    //           name: '更新',
    //           type: 'feature',
    //           featureCode: 'serviceCatalog.update',
    //           featurePoint: true,
    //           parentId: '01E31SEDAS2J275A4WWPHPKZAC',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SEFPA3WE1RC74FM6XR7H1',
    //               createdAt: '2020-03-10T16:37:14Z',
    //               updatedAt: '2020-03-10T16:37:14Z',
    //               type: 'api',
    //               featureCode: 'serviceCatalog.update.api',
    //               parentId: '01E31SEF6XBKBA9CGWF7H1D6QK',
    //               sort: 0,
    //               resourceActionId: '01E31SEFKHMRTC7A7ZHN707HZF',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SEE1R6FZ790T5XPX8D8Q9',
    //           createdAt: '2020-03-10T16:37:12Z',
    //           updatedAt: '2020-03-10T16:37:12Z',
    //           name: '查看',
    //           type: 'feature',
    //           featureCode: 'serviceCatalog.view',
    //           featurePoint: true,
    //           parentId: '01E31SEDAS2J275A4WWPHPKZAC',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SEEFPM0ZFJNDR83P0675C',
    //               createdAt: '2020-03-10T16:37:13Z',
    //               updatedAt: '2020-03-10T16:37:13Z',
    //               type: 'api',
    //               featureCode: 'serviceCatalog.view.api',
    //               parentId: '01E31SEE1R6FZ790T5XPX8D8Q9',
    //               sort: 0,
    //               resourceActionId: '01E31SEEDJR34BGPG61Q4AZHQZ',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SEEMDHGHHEJT85CA2P32E',
    //           createdAt: '2020-03-10T16:37:13Z',
    //           updatedAt: '2020-03-10T16:37:13Z',
    //           name: '删除',
    //           type: 'feature',
    //           featureCode: 'serviceCatalog.delete',
    //           featurePoint: true,
    //           parentId: '01E31SEDAS2J275A4WWPHPKZAC',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SEF2HBKGJ30E6ADZC699C',
    //               createdAt: '2020-03-10T16:37:13Z',
    //               updatedAt: '2020-03-10T16:37:13Z',
    //               type: 'api',
    //               featureCode: 'serviceCatalog.delete.api',
    //               parentId: '01E31SEEMDHGHHEJT85CA2P32E',
    //               sort: 0,
    //               resourceActionId: '01E31SEF0BT7D1312H2HTBD6H7',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //         {
    //           id: '01E31SEFTS851853QP1B8HW0PK',
    //           createdAt: '2020-03-10T16:37:14Z',
    //           updatedAt: '2020-03-10T16:37:14Z',
    //           name: '查看监控',
    //           type: 'feature',
    //           featureCode: 'serviceCatalog.monitor',
    //           featurePoint: true,
    //           parentId: '01E31SEDAS2J275A4WWPHPKZAC',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //         },
    //         {
    //           id: '01E31SEDF3QSHX7QNMCQGPTD3M',
    //           createdAt: '2020-03-10T16:37:12Z',
    //           updatedAt: '2020-03-10T16:37:12Z',
    //           name: '创建',
    //           type: 'feature',
    //           featureCode: 'serviceCatalog.create',
    //           featurePoint: true,
    //           parentId: '01E31SEDAS2J275A4WWPHPKZAC',
    //           sort: 0,
    //           level: 0,
    //           access: true,
    //           children: [
    //             {
    //               id: '01E31SEDWVR20A5SEH54AMNNTB',
    //               createdAt: '2020-03-10T16:37:12Z',
    //               updatedAt: '2020-03-10T16:37:12Z',
    //               type: 'api',
    //               featureCode: 'serviceCatalog.create.api',
    //               parentId: '01E31SEDF3QSHX7QNMCQGPTD3M',
    //               sort: 0,
    //               resourceActionId: '01E31SEDTMFNH31W96PGVJAEH1',
    //               level: 0,
    //               access: true,
    //             },
    //           ],
    //         },
    //       ],
    //     },
    //   ],
    // });
  }

  getUserById(roleId: string) {
    return this.api.get(`/authorizations/roles/${roleId}/users`);
  }
}

export default new RoleService();
