import Vue from 'vue';
import {
  Button,
  Cascader,
  DatePicker,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  CheckboxGroup,
  Checkbox,
  Input,
  Loading,
  Menu,
  MenuItem,
  MenuItemGroup,
  Option,
  OptionGroup,
  Pagination,
  Popover,
  Radio,
  RadioButton,
  RadioGroup,
  Select,
  Submenu,
  Table,
  TableColumn,
  TabPane,
  Tabs,
  Tooltip,
  Form,
  FormItem,
  Card,
  Tree,
  Divider,
  Alert,
} from 'element-ui';

import '../../assets/styles/element-variables.scss';

Vue.use(CheckboxGroup);
Vue.use(Checkbox);
Vue.use(Button);
Vue.use(Cascader);
Vue.use(DatePicker);
Vue.use(DropdownMenu);
Vue.use(Dropdown);
Vue.use(DropdownItem);
Vue.use(Input);
Vue.use(Loading);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(MenuItemGroup);
Vue.use(Option);
Vue.use(OptionGroup);
Vue.use(Pagination);
Vue.use(Popover);
Vue.use(Select);
Vue.use(Submenu);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(TabPane);
Vue.use(Tabs);
Vue.use(Tooltip);
Vue.use(Radio);
Vue.use(RadioButton);
Vue.use(RadioGroup);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Card);
Vue.use(Tree);
Vue.use(Divider);
Vue.use(Alert);
